require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/**/*
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
Metrics/AbcSize:
  Exclude:
    - db/migrate/*
